{
  lib,
  pkgs,
  ...
}: let
  browser = ''${lib.getExe pkgs.vivaldi} ${lib.concatStringsSep " " (import ../browser/common.nix).commandLineArgs} --password-store=kwallet6'';
  terminal = lib.getExe pkgs.kitty;
in {
  wayland.windowManager.hyprland.settings = {
    bind = [
      "SUPER,Return,exec,${terminal}"
      # dms
      "SUPER,Tab,exec,dms ipc call hypr toggleOverview"
      "SUPER SHIFT,Return,exec,dms ipc call spotlight toggle"
      "SUPER,V,exec, dms ipc call clipboard toggle"
      "SUPER,M,exec,dms ipc call processlist toggle"
      "SUPER,N,exec, dms ipc call notifications toggle"
      "SUPER,comma,exec, dms ipc call settings toggle"
      "SUPER,P,exec, dms ipc call notepad toggle"
      "SUPER ALT,L,exec, dms ipc call lock lock"
      "SUPER,X,exec, dms ipc call powermenu toggle"
      "SUPER,C,exec, dms ipc call control-center toggle"
      ",XF86AudioRaiseVolume,exec,dms ipc call audio increment 3"
      ",XF86AudioLowerVolume,exec,dms ipc call audio decrement 3"
      ",XF86AudioMute, exec, dms ipc call audio mute"
      ",XF86AudioMicMute, exec, dms ipc call audio micmute"
      ",XF86MonBrightnessUp,exec,dms ipc call brightness increment 5 \"\""
      ",XF86MonBrightnessDown,exec,dms ipc call brightness decrement 5 \"\""
      "SUPER SHIFT,N,exec,dms ipc call night toggle"
      # pypr
      "SUPER shift,T,exec,pypr toggle term"
      # etc
      "SUPER SHIFT,C,exec,hyprpicker -a"
      "SUPER,W,exec,${browser}"
      "SUPER,Y,exec,kitty -e yazi"
      "SUPER,S,exec,screenshootin"
      ",Print,exec,screenshootin"
      "SUPER,O,exec,obs"
      "SUPER,G,exec,gimp"
      "SUPER,T,exec, dolphin"
      "SUPER SHIFT,V,exec,code"
      # media ctl
      ",XF86AudioPlay, exec, playerctl play-pause"
      ",XF86AudioPause, exec, playerctl play-pause"
      ",XF86AudioNext, exec, playerctl next"
      ",XF86AudioPrev, exec, playerctl previous"
      # no exec
      "SUPER,Q,killactive,"
      "SUPER SHIFT,I,togglesplit,"
      "SUPER,F,fullscreen,"
      "SUPER SHIFT,F,togglefloating,"
      "SUPER CONTROL,F,fullscreenstate, 0 3"
      "SUPER ALT,F,workspaceopt, allfloat"
      "SUPER SHIFT,C,exit,"
      "SUPER SHIFT,left,movewindow,l"
      "SUPER SHIFT,right,movewindow,r"
      "SUPER SHIFT,up,movewindow,u"
      "SUPER SHIFT,down,movewindow,d"
      "SUPER SHIFT,h,movewindow,l"
      "SUPER SHIFT,l,movewindow,r"
      "SUPER SHIFT,k,movewindow,u"
      "SUPER SHIFT,j,movewindow,d"
      "SUPER ALT, left, swapwindow,l"
      "SUPER ALT, right, swapwindow,r"
      "SUPER ALT, up, swapwindow,u"
      "SUPER ALT, down, swapwindow,d"
      "SUPER ALT, 43, swapwindow,l"
      "SUPER ALT, 46, swapwindow,r"
      "SUPER ALT, 45, swapwindow,u"
      "SUPER ALT, 44, swapwindow,d"
      "SUPER,left,movefocus,l"
      "SUPER,right,movefocus,r"
      "SUPER,up,movefocus,u"
      "SUPER,down,movefocus,d"
      "SUPER,h,movefocus,l"
      "SUPER,l,movefocus,r"
      "SUPER,k,movefocus,u"
      "SUPER,j,movefocus,d"
      "SUPER,1,workspace,1"
      "SUPER,2,workspace,2"
      "SUPER,3,workspace,3"
      "SUPER,4,workspace,4"
      "SUPER,5,workspace,5"
      "SUPER,6,workspace,6"
      "SUPER,7,workspace,7"
      "SUPER,8,workspace,8"
      "SUPER,9,workspace,9"
      "SUPER,0,workspace,10"
      "SUPER SHIFT,SPACE,movetoworkspace,special"
      "SUPER,SPACE,togglespecialworkspace"
      "SUPER SHIFT,1,movetoworkspace,1"
      "SUPER SHIFT,2,movetoworkspace,2"
      "SUPER SHIFT,3,movetoworkspace,3"
      "SUPER SHIFT,4,movetoworkspace,4"
      "SUPER SHIFT,5,movetoworkspace,5"
      "SUPER SHIFT,6,movetoworkspace,6"
      "SUPER SHIFT,7,movetoworkspace,7"
      "SUPER SHIFT,8,movetoworkspace,8"
      "SUPER SHIFT,9,movetoworkspace,9"
      "SUPER SHIFT,0,movetoworkspace,10"
      "SUPER CONTROL,right,workspace,e+1"
      "SUPER CONTROL,left,workspace,e-1"
      "SUPER,mouse_down,workspace, e+1"
      "SUPER,mouse_up,workspace, e-1"
      "ALT,Tab,cyclenext"
      "ALT,Tab,bringactivetotop"
      # plugin
      # "SUPER CONTROL,page_up,backcyclevdesks"
      # "SUPER CONTROL,page_down,cyclevdesks"
      # "SUPER SHIFT,page_up,movetoprevdesk"
      # "SUPER SHIFT,page_down,movetonextdesk"
      # "SUPER CONTROL,up,backcyclevdesks"
      # "SUPER CONTROL,down,cyclevdesks"
      "SUPER SHIFT,Q,plugin:xtd:closeunfocused"
      "SUPER CONTROL,1,plugin:xtd:throwunfocused,1"
      "SUPER CONTROL,2,plugin:xtd:throwunfocused,2"
      "SUPER CONTROL,3,plugin:xtd:throwunfocused,3"
      "SUPER CONTROL,4,plugin:xtd:throwunfocused,4"
      "SUPER CONTROL,5,plugin:xtd:throwunfocused,5"
      "SUPER CONTROL,6,plugin:xtd:throwunfocused,6"
      "SUPER CONTROL,7,plugin:xtd:throwunfocused,7"
      "SUPER CONTROL,8,plugin:xtd:throwunfocused,8"
      "SUPER CONTROL,9,plugin:xtd:throwunfocused,9"
      "SUPER CONTROL,0,plugin:xtd:throwunfocused,10"
      "SUPER CONTROL,page_up,plugin:xtd:throwunfocused,e-1"
      "SUPER CONTROL,page_down,plugin:xtd:throwunfocused,e+1"
    ];

    bindm = [
      "SUPER, mouse:272, movewindow"
      "SUPER, Control_L, movewindow"
      "SUPER, mouse:273, resizewindow"
      "SUPER, ALT_L, resizewindow"
    ];

    gesture = [
      "4, horizontal, workspace"
      "4, up, dispatcher, exec, dms ipc call hypr closeOverview"
      "4, down, dispatcher, exec, dms ipc call hypr openOverview"
      "3, down, mod: ALT, close"
      "3, down, dispatcher, exec, pypr show term"
      "3, up, dispatcher, exec, pypr hide term"
      "3, pinchin, dispatcher, fullscreen, 0 set"
      "3, pinchout, dispatcher, fullscreen, 0 unset"
    ];
  };
}
