{
  osConfig,
  lib,
  ...
}: let
  inherit (lib.generators) toLua;
  hw = osConfig.zerozawa.hardware;
in ''
  -- Auto-generated by Nix. Do not edit.
  return ${toLua {} {
    hardware = {
      isNvidiaGPU = hw.isNvidiaGPU;
      isAmdGPU = hw.isAmdGPU;
      isIntelGPU = hw.isIntelGPU;
      isIntelCPU = hw.isIntelCPU;
      isAMDCPU = hw.isAMDCPU;
      isLaptop = hw.isLaptop;
      isSSD = hw.isSSD;
      isFingerprint = hw.isFingerprint;
      isOculink = hw.isOculink;
      ram = hw.ram;
      amd64Microarchs = hw.amd64Microarchs;
      drm = {
        aqDrmDevices = hw.drm.aqDrmDevices;
      };
    };
    features = {
      nm_applet = osConfig.networking.networkmanager.enable or false;
    };
  }}
''
