hl.window_rule({ match = { xwayland = true }, no_blur = true })
hl.window_rule({ match = { xwayland = true, class = "^(\\bresolve\\b)$" }, no_blur = true })

hl.window_rule({ match = { class = "^([Tt]hunar|org.gnome.Nautilus|[Pp]cmanfm-qt)$" }, tag = "+file-manager" })
hl.window_rule({ match = { class = "^(com.mitchellh.ghostty|org.wezfurlong.wezterm|Alacritty|kitty|kitty-dropterm)$" }, tag = "+terminal" })
hl.window_rule({ match = { class = "^(Brave-browser(-beta|-dev|-unstable)?)$" }, tag = "+browser" })
hl.window_rule({ match = { class = "^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr)$" }, tag = "+browser" })
hl.window_rule({ match = { class = "^([Gg]oogle-chrome(-beta|-dev|-unstable)?)$" }, tag = "+browser" })
hl.window_rule({ match = { class = "^([Tt]horium-browser|[Cc]achy-browser)$" }, tag = "+browser" })
hl.window_rule({ match = { class = "^(codium|codium-url-handler|VSCodium)$" }, tag = "+projects" })
hl.window_rule({ match = { class = "^(VSCode|code-url-handler)$" }, tag = "+projects" })
hl.window_rule({ match = { class = "^([Dd]iscord|[Ww]ebCord|[Vv]esktop)$" }, tag = "+im" })
hl.window_rule({ match = { class = "^([Ff]erdium)$" }, tag = "+im" })
hl.window_rule({ match = { class = "^([Ww]hatsapp-for-linux)$" }, tag = "+im" })
hl.window_rule({ match = { class = "^(org.telegram.desktop|io.github.tdesktop_x64.TDesktop)$" }, tag = "+im" })
hl.window_rule({ match = { class = "^(teams-for-linux)$" }, tag = "+im" })
hl.window_rule({ match = { class = "^(gamescope)$" }, tag = "+games" })
hl.window_rule({ match = { class = "^(steam_app_\\d+)$" }, tag = "+games" })
hl.window_rule({ match = { class = "^([Ss]team)$" }, tag = "+gamestore" })
hl.window_rule({ match = { title = "^([Ll]utris)$" }, tag = "+gamestore" })
hl.window_rule({ match = { class = "^(com.heroicgameslauncher.hgl)$" }, tag = "+gamestore" })
hl.window_rule({ match = { class = "^(gnome-disks|wihotspot(-gui)?)$" }, tag = "+settings" })
hl.window_rule({ match = { class = "^([Rr]ofi)$" }, tag = "+settings" })
hl.window_rule({ match = { class = "^(file-roller|org.gnome.FileRoller)$" }, tag = "+settings" })
hl.window_rule({ match = { class = "^(nm-applet|nm-connection-editor|blueman-manager)$" }, tag = "+settings" })
hl.window_rule({ match = { class = "^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$" }, tag = "+settings" })
hl.window_rule({ match = { class = "^(nwg-look|qt5ct|qt6ct|[Yy]ad)$" }, tag = "+settings" })
hl.window_rule({ match = { class = "(xdg-desktop-portal-gtk)" }, tag = "+settings" })
hl.window_rule({ match = { class = "(.blueman-manager-wrapped)" }, tag = "+settings" })
hl.window_rule({ match = { class = "(nwg-displays)" }, tag = "+settings" })

hl.window_rule({ match = { title = "^(Picture-in-Picture)$" }, move = "72% 7%", float = true, opacity = "0.95 0.75", pin = true, keep_aspect_ratio = true })
hl.window_rule({ match = { class = "^([Ff]erdium)$" }, center = true })
hl.window_rule({ match = { class = "^([Ww]aypaper)$" }, float = true })
hl.window_rule({ match = { class = "^(pavucontrol|org.pulseaudio.pavucontrol|com.saivert.pwvucontrol)$" }, center = true })
hl.window_rule({ match = { class = "([Tt]hunar)", title = "negative:(.*[Tt]hunar.*)" }, center = true })
hl.window_rule({ match = { title = "^(Authentication Required)$" }, center = true })
hl.window_rule({ match = { class = "^(*)$" }, idle_inhibit = "fullscreen" })
hl.window_rule({ match = { title = "^(*)$" }, idle_inhibit = "fullscreen" })
hl.window_rule({ match = { fullscreen = true }, idle_inhibit = "fullscreen" })
hl.window_rule({ match = { tag = "settings*" }, float = true, size = "70% 70%", opacity = "0.8 0.7" })
hl.window_rule({ match = { class = "^([Ff]erdium)$" }, float = true, size = "60% 70%" })
hl.window_rule({ match = { class = "^(mpv|com.github.rafostar.Clapper)$" }, float = true })
hl.window_rule({ match = { title = "^(Authentication Required)$" }, float = true })
hl.window_rule({ match = { class = "(codium|codium-url-handler|VSCodium)", title = "negative:(.*codium.*|.*VSCodium.*)" }, float = true })
hl.window_rule({ match = { class = "^(com.heroicgameslauncher.hgl)$", title = "negative:(Heroic Games Launcher)" }, float = true })
hl.window_rule({ match = { class = "^([Ss]team)$", title = "negative:^([Ss]team)$" }, float = true })
hl.window_rule({ match = { class = "([Tt]hunar)", title = "negative:(.*[Tt]hunar.*)" }, float = true })
hl.window_rule({ match = { initial_title = "(Add Folder to Workspace)" }, float = true, size = "70% 60%" })
hl.window_rule({ match = { initial_title = "(Open Files)" }, float = true, size = "70% 60%" })
hl.window_rule({ match = { initial_title = "(wants to save)" }, float = true })

hl.window_rule({ match = { tag = "browser*" }, opacity = "1.0 1.0" })
hl.window_rule({ match = { tag = "projects*" }, opacity = "0.9 0.8" })
hl.window_rule({ match = { tag = "im*" }, opacity = "0.94 0.86" })
hl.window_rule({ match = { tag = "file-manager*" }, opacity = "0.9 0.8" })
hl.window_rule({ match = { tag = "terminal*" }, opacity = "0.9 0.8", force_rgbx = true })
hl.window_rule({ match = { class = "^(gedit|org.gnome.TextEditor|mousepad)$" }, opacity = "0.8 0.7" })
hl.window_rule({ match = { class = "^(seahorse)$" }, opacity = "0.9 0.8" })
hl.window_rule({ match = { class = "^(mpv|com.github.rafostar.Clapper)$" }, opacity = "1.0 1.0" })

hl.window_rule({ match = { tag = "games*" }, no_blur = true, fullscreen = true })
hl.window_rule({ match = { class = "Waydroid" }, fullscreen = true })
hl.window_rule({ match = { class = "labwc" }, fullscreen = true })
hl.window_rule({ match = { class = "^([Vv]ivaldi ((Settings)|(设置)).*))$" }, float = true })
hl.window_rule({ match = { class = "wechat" }, float = true })
hl.window_rule({ match = { class = "QQ" }, float = true })
hl.window_rule({ match = { title = "^(DevTools.*)$", initial_class = "^((code)|(chromium-browser))$" }, float = true })
hl.window_rule({ match = { class = "^(xwaylandvideobridge)$" }, opacity = "0.0 override", size = "0% 0%" })
hl.window_rule({ match = { class = "kitty-dropterm" }, float = true })
