# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  modulesPath,
  isIntelCPU,
  lib,
  ...
}:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ]
    ++ (lib.optionals isIntelCPU [ "./intel/cpu.nix" ])
    ++ [
      ./hostname
    ];
}
