{
  lib,
  pkgs,
  ...
}: let
  browser = ''${lib.getExe pkgs.vivaldi} ${lib.concatStringsSep " " (import ../../browser/common.nix).commandLineArgs} --password-store=kwallet6'';
  terminal = lib.getExe pkgs.kitty;
in {
  wayland.windowManager.hyprland.settings = {
    bind = [
      "$modifier,Return,exec,${terminal}"
      # dms
      "$modifier,Tab,exec,dms ipc call hypr toggleOverview"
      "$modifier SHIFT,Return,exec,dms ipc call spotlight toggle"
      "$modifier,V,exec, dms ipc call clipboard toggle"
      "$modifier,M,exec,dms ipc call processlist toggle"
      "$modifier,N,exec, dms ipc call notifications toggle"
      "$modifier,comma,exec, dms ipc call settings toggle"
      "$modifier,P,exec, dms ipc call notepad toggle"
      "$modifier ALT,L,exec, dms ipc call lock lock"
      "$modifier,X,exec, dms ipc call powermenu toggle"
      "$modifier,C,exec, dms ipc call control-center toggle"
      ",XF86AudioRaiseVolume,exec,dms ipc call audio increment 3"
      ",XF86AudioLowerVolume,exec,dms ipc call audio decrement 3"
      ",XF86AudioMute, exec, dms ipc call audio mute"
      ",XF86AudioMicMute, exec, dms ipc call audio micmute"
      ",XF86MonBrightnessUp,exec,dms ipc call brightness increment 5 \"\""
      ",XF86MonBrightnessDown,exec,dms ipc call brightness decrement 5 \"\""
      "$modifier SHIFT,N,exec,dms ipc call night toggle"
      # rofi
      "$modifier SHIFT,W,exec,web-search"
      # pypr
      "$modifier shift,T,exec,pypr toggle term"
      # etc
      "$modifier SHIFT,C,exec,hyprpicker -a"
      "$modifier,W,exec,${browser}"
      "$modifier,Y,exec,kitty -e yazi"
      "$modifier,S,exec,screenshootin"
      ",Print,exec,screenshootin"
      "$modifier,O,exec,obs"
      "$modifier,G,exec,gimp"
      "$modifier,T,exec, dolphin"
      "$modifier SHIFT,V,exec,code"
      # media ctl
      ",XF86AudioLowerVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
      ",XF86AudioPlay, exec, playerctl play-pause"
      ",XF86AudioPause, exec, playerctl play-pause"
      ",XF86AudioNext, exec, playerctl next"
      ",XF86AudioPrev, exec, playerctl previous"
      # no exec
      "$modifier,Q,killactive,"
      "$modifier SHIFT,I,togglesplit,"
      "$modifier,F,fullscreen,"
      "$modifier SHIFT,F,togglefloating,"
      "$modifier CONTROL,F,fullscreenstate, 0 3"
      "$modifier ALT,F,workspaceopt, allfloat"
      "$modifier SHIFT,C,exit,"
      "$modifier SHIFT,left,movewindow,l"
      "$modifier SHIFT,right,movewindow,r"
      "$modifier SHIFT,up,movewindow,u"
      "$modifier SHIFT,down,movewindow,d"
      "$modifier SHIFT,h,movewindow,l"
      "$modifier SHIFT,l,movewindow,r"
      "$modifier SHIFT,k,movewindow,u"
      "$modifier SHIFT,j,movewindow,d"
      "$modifier ALT, left, swapwindow,l"
      "$modifier ALT, right, swapwindow,r"
      "$modifier ALT, up, swapwindow,u"
      "$modifier ALT, down, swapwindow,d"
      "$modifier ALT, 43, swapwindow,l"
      "$modifier ALT, 46, swapwindow,r"
      "$modifier ALT, 45, swapwindow,u"
      "$modifier ALT, 44, swapwindow,d"
      "$modifier,left,movefocus,l"
      "$modifier,right,movefocus,r"
      "$modifier,up,movefocus,u"
      "$modifier,down,movefocus,d"
      "$modifier,h,movefocus,l"
      "$modifier,l,movefocus,r"
      "$modifier,k,movefocus,u"
      "$modifier,j,movefocus,d"
      "$modifier,1,workspace,1"
      "$modifier,2,workspace,2"
      "$modifier,3,workspace,3"
      "$modifier,4,workspace,4"
      "$modifier,5,workspace,5"
      "$modifier,6,workspace,6"
      "$modifier,7,workspace,7"
      "$modifier,8,workspace,8"
      "$modifier,9,workspace,9"
      "$modifier,0,workspace,10"
      "$modifier SHIFT,SPACE,movetoworkspace,special"
      "$modifier,SPACE,togglespecialworkspace"
      "$modifier SHIFT,1,movetoworkspace,1"
      "$modifier SHIFT,2,movetoworkspace,2"
      "$modifier SHIFT,3,movetoworkspace,3"
      "$modifier SHIFT,4,movetoworkspace,4"
      "$modifier SHIFT,5,movetoworkspace,5"
      "$modifier SHIFT,6,movetoworkspace,6"
      "$modifier SHIFT,7,movetoworkspace,7"
      "$modifier SHIFT,8,movetoworkspace,8"
      "$modifier SHIFT,9,movetoworkspace,9"
      "$modifier SHIFT,0,movetoworkspace,10"
      "$modifier CONTROL,right,workspace,e+1"
      "$modifier CONTROL,left,workspace,e-1"
      # "$modifier CONTROL,up,backcyclevdesks"
      # "$modifier CONTROL,down,cyclevdesks"
      "$modifier,mouse_down,workspace, e+1"
      "$modifier,mouse_up,workspace, e-1"
      # "$modifier CONTROL,page_up,backcyclevdesks"
      # "$modifier CONTROL,page_down,cyclevdesks"
      # "$modifier SHIFT,page_up,movetoprevdesk"
      # "$modifier SHIFT,page_down,movetonextdesk"
      "ALT,Tab,cyclenext"
      "ALT,Tab,bringactivetotop"
    ];

    bindm = [
      "$modifier, mouse:272, movewindow"
      "$modifier, mouse:273, resizewindow"
    ];
  };
}
