# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  pkgs,
  ...
}:

{
  boot.kernelPackages = pkgs.linuxPackages_cachyos;
}
